# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4961f306e903fc70787770766cf62834433cf1af9e7598cdbdf912420e5a54a33b56988b8ea87504cef41fd6d677bb177c143653b43e4bb24acfa6d295e17b6

test:
  secret_key_base: 23168434afdec663c730c495090fef988a5713963c4102138a6b74b43ed0c5c8e6bedd4a764cc811262dfd80263b9a57341e306dce84ae46a9855eca0a206fdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
